#!/usr/bin/env bash
#
# Written by Denilson Figueiredo de Sá <denilsonsa@gmail.com>
# MIT license
#
# Requirements:
# * bash (tested on 4.20, should work on older versions too)
# * awk (works with GNU awk, nawk, busybox awk, mawk)
# * ping (from iputils)

print_help() {
	cat << EOF
Usage: $MYNAME [prettyping parameters] <standard ping parameters>

This script is a wrapper around the system's "ping" tool. It will substitute
each ping response line by a colored character, giving a very compact overview
of the ping responses.

prettyping parameters:
  --[no]color      Enable/disable color output. (default: enabled)
  --[no]multicolor Enable/disable multi-color unicode output. Has no effect if
                     either color or unicode is disabled. (default: enabled)
  --[no]unicode    Enable/disable unicode characters. (default: enabled)
  --[no]legend     Enable/disable the latency legend. (default: enabled)
  --[no]terminal   Force the output designed to a terminal. (default: auto)
  --last <n>       Use the last "n" pings at the statistics line. (default: 60)
  --columns <n>    Override auto-detection of terminal dimensions.
  --lines <n>      Override auto-detection of terminal dimensions.
  --rttmin <n>     Minimum RTT represented in the unicode graph. (default: auto)
  --rttmax <n>     Maximum RTT represented in the unicode graph. (default: auto)
  --awkbin <exec>  Override the awk interpreter. (default: awk)
  --pingbin <exec> Override the ping tool. (default: ping)
  --time           Print the current time at the beginning of each line (requires gawk).
  -a, --audible    Play the terminal bell on successful ping.
  -6               Shortcut for: --pingbin ping6

ping parameters handled by prettyping:
  -f  Flood mode is not allowed in prettyping.
  -q  Quiet output is not allowed in prettyping.
  -R  Record route mode is not allowed in prettyping.
  -v  Verbose output seems to be the default mode in ping.

All other parameters are passed directly to ping.
EOF
}

parse_arguments() {
	USE_COLOR=1
	USE_MULTICOLOR=1
	USE_UNICODE=1
	USE_LEGEND=1
	PRINT_TIME=0
	AUDIBLE=0

	if [ -t 1 ]; then
		IS_TERMINAL=1
	else
		IS_TERMINAL=0
	fi

	LAST_N=60
	OVERRIDE_COLUMNS=0
	OVERRIDE_LINES=0
	RTT_MIN=auto
	RTT_MAX=auto

	PING_BIN="ping"
	PING_PARAMS=( )

	AWK_BIN="awk"
	AWK_PARAMS=( )

	while [[ $# != 0 ]] ; do
		case "$1" in
			-h | -help | --help )
				print_help
				exit
				;;

			-f ) echo "${MYNAME}: You can't use the -f (flood) option." >&2; exit 1 ;;
			-R ) echo "${MYNAME}: You can't use the -R (record route) option." >&2; exit 1 ;;
			-q ) echo "${MYNAME}: You can't use the -q (quiet) option." >&2; exit 1 ;;
			-v ) ;;

			-a | --audible ) AUDIBLE=1 ;;
			--time ) PRINT_TIME=1 ;;

			-color        | --color        ) USE_COLOR=1 ;;
			-nocolor      | --nocolor      ) USE_COLOR=0 ;;
			-multicolor   | --multicolor   ) USE_MULTICOLOR=1 ;;
			-nomulticolor | --nomulticolor ) USE_MULTICOLOR=0 ;;
			-unicode      | --unicode      ) USE_UNICODE=1 ;;
			-nounicode    | --nounicode    ) USE_UNICODE=0 ;;
			-legend       | --legend       ) USE_LEGEND=1 ;;
			-nolegend     | --nolegend     ) USE_LEGEND=0 ;;
			-terminal     | --terminal     ) IS_TERMINAL=1 ;;
			-noterminal   | --noterminal   ) IS_TERMINAL=0 ;;
			-6 ) PING_BIN="ping6" ;;

			-awkbin  | --awkbin  ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; AWK_BIN="$2"; shift ;;
			-pingbin | --pingbin ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; PING_BIN="$2"; shift ;;
			-last    | --last    ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; LAST_N="$2"; shift ;;
			-columns | --columns ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; OVERRIDE_COLUMNS="$2"; shift ;;
			-lines   | --lines   ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; OVERRIDE_LINES="$2"; shift ;;
			-rttmin  | --rttmin  ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; RTT_MIN="$2"; shift ;;
			-rttmax  | --rttmax  ) if [[ -z "${2:-}" ]]; then echo "${MYNAME}: $1 requires an argument." >&2; exit 1; fi; RTT_MAX="$2"; shift ;;

			* ) PING_PARAMS+=("$1") ;;
		esac
		shift
	done

	if [[ "${RTT_MIN}" =~ ^[0-9]+$ && "${RTT_MAX}" =~ ^[0-9]+$ ]] ; then
		if [[ "${RTT_MIN}" -ge "${RTT_MAX}" ]] ; then
			echo "${MYNAME}: Invalid --rttmin and --rttmax values." >&2
			exit 1
		fi
	fi

	if [[ "${#PING_PARAMS[@]}" = 0 ]] ; then
		echo "${MYNAME}: Missing parameters, use --help for instructions." >&2
		exit 1
	fi

	local version="$(echo | "${AWK_BIN}" -W version 2>&1)"
	if [[ "${version}" == mawk* ]] ; then
		AWK_PARAMS+=(-W interactive)
	fi
}

MYNAME=$(basename "$0")
parse_arguments "$@"

export LC_ALL=C
export USE_COLOR USE_MULTICOLOR USE_UNICODE USE_LEGEND IS_TERMINAL LAST_N
export OVERRIDE_COLUMNS OVERRIDE_LINES RTT_MIN RTT_MAX

trap '' 2

run_ping() {
	"${PING_BIN}" "${PING_PARAMS[@]}" &
	PING_PID="$!"
	trap 'kill "$PING_PID" 2>/dev/null' EXIT
	wait "$PING_PID"
}

filter_winch() {
	if [ "${IS_TERMINAL}" = 1 ]; then
		(
			trap "echo SIGWINCH" WINCH
			while IFS= read -r line; do
				printf "%s\n" "$line"
			done
		)
	else
		cat
	fi
}

run_ping 2>&1 | filter_winch 2>&1 | "${AWK_BIN}" "${AWK_PARAMS[@]}" -v PRINT_TIME="$PRINT_TIME" -v AUDIBLE="$AUDIBLE" '

function abs(x) {
	return ( (x < 0) ? -x : x )
}

function ceil(x) {
	return (x == int(x)) ? x : int(x) + 1
}

function get_terminal_size(SIZE, SIZEA, HAS_DETECTED, CMD) {
	HAS_DETECTED = 0

	CMD = "stty size < /dev/tty 2> /dev/null"

	if ( (CMD | getline SIZE) == 1 ) {
		split(SIZE, SIZEA, " ")
		LINES   = int(SIZEA[1])
		COLUMNS = int(SIZEA[2])
		HAS_DETECTED = 1
	}
	close(CMD)

	if ( HAS_DETECTED == 0 ) {
		CMD = "tput lines"
		if ( (CMD | getline SIZE) == 1 ) {
			LINES = int(SIZE)
			HAS_DETECTED = 1
		}
		close(CMD)

		CMD = "tput cols"
		if ( (CMD | getline SIZE) == 1 ) {
			COLUMNS = int(SIZE)
			HAS_DETECTED = 1
		}
		close(CMD)
	}

	if ( int(ENVIRON["OVERRIDE_COLUMNS"]) ) { COLUMNS = int(ENVIRON["OVERRIDE_COLUMNS"]) }
	if ( int(ENVIRON["OVERRIDE_LINES"])   ) { LINES   = int(ENVIRON["OVERRIDE_LINES"])   }
}

function other_line_is_printed() {
	if ( IS_PRINTING_DOTS ) {
		if ( IS_TERMINAL ) {
			printf( ESC_DEFAULT ESC_NEXTLINE ESC_NEXTLINE "\n" )
		} else {
			printf( ESC_DEFAULT "\n" )
			print_statistics_bar()
		}
	}
	IS_PRINTING_DOTS = 0
	CURR_COL = 0
}

function other_line_is_repeated() {
	if ( other_line_times < 2 ) {
		return
	}
	if ( IS_TERMINAL ) {
		printf( ESC_DEFAULT ESC_ERASELINE "\r" )
	}
	printf( "Last message repeated %d times.", other_line_times )
	if ( ! IS_TERMINAL ) {
		printf( "\n" )
	}
}

function other_line_finished_repeating() {
	if ( other_line_times >= 2 ) {
		if ( IS_TERMINAL ) {
			printf( "\n" )
		} else {
			other_line_is_repeated()
		}
	}
	other_line = ""
	other_line_times = 0
}

function print_newlines_if_needed() {
	if ( IS_TERMINAL ) {
		if ( CURR_COL >= COLUMNS-1 ) {
			CURR_COL = 0
		}
		if ( CURR_COL == 0 ) {
			if ( IS_PRINTING_DOTS ) {
				printf( "\n" )
			}
			printf( ESC_DEFAULT "\n" "\n" ESC_CURSORUP ESC_CURSORUP ESC_ERASELINE )
			
			if ( PRINT_TIME ) {
				ts = strftime("[%H:%M:%S] ")
				printf( "%s", ts )
				CURR_COL += length(ts)
			}
		}
	} else {
		if ( CURR_COL >= LAST_N ) {
			CURR_COL = 0
			printf( ESC_DEFAULT "\n" )
			print_statistics_bar()
		}
	}
	IS_PRINTING_DOTS = 1
}

function clear(d) {
	d["index"] = 0
	d["size"]  = 0
}

function store(d, value) {
	d[d["index"]] = value
	d["index"]++
	if ( d["index"] >= d["size"] ) {
		if ( d["size"] < LAST_N ) {
			d["size"]++
		} else {
			d["index"] = 0
		}
	}
}

function process_rtt(rtt) {
	last_rtt = rtt
	total_rtt += rtt

	if ( !first_received ) {
		min_rtt = max_rtt = rtt
		first_received = 1
	} else {
		if ( rtt < min_rtt ) min_rtt = rtt
		if ( rtt > max_rtt ) max_rtt = rtt
	}

	store(lastn_rtt, rtt)

	if ( AUDIBLE ) {
		printf( "\a" )
	}
}

function lost_a_packet() {
	print_newlines_if_needed()
	print_missing_response()

	last_seq++
	lost++
	store(lastn_lost, 1)
}

function print_response_legend(i, n, w) {
	if ( ! USE_LEGEND ) {
		return
	}
	if ( BLOCK_LEN > 1 ) {
		w = 0
		n = "0 "
		w += length(n) + 1

		printf( "%s%s%s", n, BLOCK[0], ESC_DEFAULT )

		for ( i=1 ; i<BLOCK_LEN ; i++ ) {
			n = sprintf( "%d ", BLOCK_RTT_MIN + ceil((i-1) * BLOCK_RTT_RANGE / (BLOCK_LEN - 2)) )
			w += length(n) + 1

			if ( IS_TERMINAL && w + 1 >= COLUMNS ) {
				printf( "\n" )
				w = length(n) + 1
			} else {
				printf( " " )
				w += 1
			}

			printf( "%s%s%s", n, BLOCK[i], ESC_DEFAULT )
		}
		printf( " ∞\n" )
	}
}

function print_received_response(rtt, block_index) {
	if ( rtt < BLOCK_RTT_MIN ) {
		block_index = 0
	} else if ( rtt >= BLOCK_RTT_MAX ) {
		block_index = BLOCK_LEN - 1
	} else {
		block_index = 1 + int((rtt - BLOCK_RTT_MIN) * (BLOCK_LEN - 2) / BLOCK_RTT_RANGE)
	}
	printf( BLOCK[block_index] )
	CURR_COL++
}

function print_received_response_colored(rtt, color_override, block_index, glyph) {
	if ( rtt < BLOCK_RTT_MIN ) {
		block_index = 0
	} else if ( rtt >= BLOCK_RTT_MAX ) {
		block_index = BLOCK_LEN - 1
	} else {
		block_index = 1 + int((rtt - BLOCK_RTT_MIN) * (BLOCK_LEN - 2) / BLOCK_RTT_RANGE)
	}
	
	glyph = BLOCK[block_index]
	gsub(/\033\[[0-9;]*m/, "", glyph)
	
	printf( "%s%s%s", color_override, glyph, ESC_DEFAULT )
	CURR_COL++
}

function print_missing_response() {
	printf( ESC_RED "!" )
	CURR_COL++
}

function print_overall(percentage_lost, avg_rtt) {
	avg_rtt = ( received > 0 ) ? (total_rtt/received) : 0
	percentage_lost = ( lost+received > 0 ) ? (lost*100/(lost+received)) : 0

	if ( IS_TERMINAL ) {
		printf( "Target: " ESC_BOLD "%s" ESC_DEFAULT \
				" | %2d/%3d (%2d%%) lost" \
				"; %4.0f/" ESC_BOLD "%4.0f" ESC_DEFAULT "/%4.0fms" \
				"; last: " ESC_BOLD "%4.0f" ESC_DEFAULT "ms" \
				" [" ESC_CYAN "dup:%d" ESC_DEFAULT " " ESC_MAGENTA "oop:%d" ESC_DEFAULT "]",
				DESTINATION, lost, lost+received, percentage_lost,
				min_rtt, avg_rtt, max_rtt, last_rtt,
				dup_count, oop_count )
	} else {
		printf( "Target: %s | %2d/%3d (%2d%%) lost; %4.0f/" ESC_BOLD "%4.0f" ESC_DEFAULT "/%4.0fms [dup:%d oop:%d]",
				DESTINATION, lost, lost+received, percentage_lost,
				min_rtt, avg_rtt, max_rtt, dup_count, oop_count )
	}
}

function print_last_n(i, percentage_lost, sum, min, avg, max, diffs, pad_str, pad_len) {
	sum = 0
	for ( i=0 ; i<lastn_lost["size"] ; i++ ) {
		sum += lastn_lost[i]
	}
	percentage_lost = (lastn_lost["size"] > 0) ? (sum*100/lastn_lost["size"]) : 0

	pad_len = 11 + length(DESTINATION)
	pad_str = sprintf("%-*s", pad_len, "")

	printf( "%s%2d/%3d (%2d%%) lost; ",
		pad_str,
		sum,
		lastn_lost["size"],
		percentage_lost )

	sum = diffs = 0
	min = max = lastn_rtt[0]
	for ( i=0 ; i<lastn_rtt["size"] ; i++ ) {
		sum += lastn_rtt[i]
		if ( lastn_rtt[i] < min ) min = lastn_rtt[i]
		if ( lastn_rtt[i] > max ) max = lastn_rtt[i]
	}
	avg = (lastn_rtt["size"]) ? (sum/lastn_rtt["size"]) : 0

	for ( i=0 ; i<lastn_rtt["size"] ; i++ ) {
		diffs += abs(lastn_rtt[i] - avg)
	}
	if ( lastn_rtt["size"] > 0 ) {
		diffs /= lastn_rtt["size"]
	}

	printf( "%4.0f/" ESC_BOLD "%4.0f" ESC_DEFAULT "/%4.0f/%4.0fms (last %d)",
		min,
		avg,
		max,
		diffs,
		lastn_rtt["size"] )
}

function print_statistics_bar() {
	if ( IS_TERMINAL ) {
		printf( ESC_SAVEPOS ESC_DEFAULT )
		printf( ESC_NEXTLINE ESC_ERASELINE )
		print_overall()
		printf( ESC_NEXTLINE ESC_ERASELINE )
		print_last_n()
		printf( ESC_UNSAVEPOS )
	} else {
		print_overall()
		printf( "\n" )
		print_last_n()
		printf( "\n" )
	}
}

function print_statistics_bar_if_terminal() {
	if ( IS_TERMINAL ) {
		print_statistics_bar()
	}
}

BEGIN {
	FS = "="
	last_seq = 0
	first_received = 0
	dup_count = 0
	oop_count = 0
	
	other_line = ""
	other_line_times = 0
	IS_PRINTING_DOTS = 0
	CURR_COL = 0
	received = 0
	lost = 0
	total_rtt = 0
	min_rtt = 0
	max_rtt = 0
	last_rtt = 0
	DESTINATION = "Unknown"

	USE_COLOR       = int(ENVIRON["USE_COLOR"])
	USE_MULTICOLOR  = int(ENVIRON["USE_MULTICOLOR"])
	USE_UNICODE     = int(ENVIRON["USE_UNICODE"])
	USE_LEGEND      = int(ENVIRON["USE_LEGEND"])
	IS_TERMINAL     = int(ENVIRON["IS_TERMINAL"])
	LAST_N          = int(ENVIRON["LAST_N"])
	
	clear(lastn_lost)
	clear(lastn_rtt)

	LINES    = 24
	COLUMNS  = 80

	get_terminal_size()
	if ( IS_TERMINAL && COLUMNS <= 50 ) {
		print "Warning: terminal width is too small."
	}

	if ( USE_COLOR ) {
		ESC_DEFAULT = "\033[0m"
		ESC_BOLD    = "\033[1m"
		ESC_RED     = "\033[0;31m"
		ESC_GREEN   = "\033[0;32m"
		ESC_YELLOW  = "\033[0;33m"
		ESC_BLUE    = "\033[0;34m"
		ESC_MAGENTA = "\033[0;35m"
		ESC_CYAN    = "\033[0;36m"
		ESC_WHITE   = "\033[0;37m"
		ESC_YELLOW_ON_GREEN = "\033[42;33m"
		ESC_RED_ON_YELLOW   = "\033[43;31m"
	}

	ESC_NEXTLINE     = "\n"
	ESC_CURSORUP     = "\033[A"
	ESC_CURSORDOWN   = "\033[B"
	ESC_SCROLLUP     = "\033[S"
	ESC_SCROLLDOWN   = "\033[T"
	ESC_ERASELINEEND = "\033[0K"
	ESC_ERASELINE    = "\033[2K"
	ESC_SAVEPOS      = "\0337"
	ESC_UNSAVEPOS    = "\0338"

	if ( USE_UNICODE ) {
		BLOCK[ 0] = ESC_GREEN "▁"
		BLOCK[ 1] = ESC_GREEN "▂"
		BLOCK[ 2] = ESC_GREEN "▃"
		BLOCK[ 3] = ESC_GREEN "▄"
		BLOCK[ 4] = ESC_GREEN "▅"
		BLOCK[ 5] = ESC_GREEN "▆"
		BLOCK[ 6] = ESC_GREEN "▇"
		BLOCK[ 7] = ESC_GREEN "█"
		BLOCK[ 8] = ESC_YELLOW_ON_GREEN "▁"
		BLOCK[ 9] = ESC_YELLOW_ON_GREEN "▂"
		BLOCK[10] = ESC_YELLOW_ON_GREEN "▃"
		BLOCK[11] = ESC_YELLOW_ON_GREEN "▄"
		BLOCK[12] = ESC_YELLOW_ON_GREEN "▅"
		BLOCK[13] = ESC_YELLOW_ON_GREEN "▆"
		BLOCK[14] = ESC_YELLOW_ON_GREEN "▇"
		BLOCK[15] = ESC_YELLOW_ON_GREEN "█"
		BLOCK[16] = ESC_RED_ON_YELLOW "▁"
		BLOCK[17] = ESC_RED_ON_YELLOW "▂"
		BLOCK[18] = ESC_RED_ON_YELLOW "▃"
		BLOCK[19] = ESC_RED_ON_YELLOW "▄"
		BLOCK[20] = ESC_RED_ON_YELLOW "▅"
		BLOCK[21] = ESC_RED_ON_YELLOW "▆"
		BLOCK[22] = ESC_RED_ON_YELLOW "▇"
		BLOCK[23] = ESC_RED_ON_YELLOW "█"
		if ( USE_MULTICOLOR && USE_COLOR ) {
			BLOCK_LEN = 24
			BLOCK_RTT_MIN = 10
			BLOCK_RTT_MAX = 230
		} else {
			BLOCK_LEN = 8
			BLOCK_RTT_MIN = 25
			BLOCK_RTT_MAX = 175
		}
	} else {
		BLOCK[ 0] = ESC_GREEN "_"
		BLOCK[ 1] = ESC_GREEN "."
		BLOCK[ 2] = ESC_GREEN "o"
		BLOCK[ 3] = ESC_GREEN "O"
		BLOCK[ 4] = ESC_YELLOW "_"
		BLOCK[ 5] = ESC_YELLOW "."
		BLOCK[ 6] = ESC_YELLOW "o"
		BLOCK[ 7] = ESC_YELLOW "O"
		BLOCK[ 8] = ESC_RED "_"
		BLOCK[ 9] = ESC_RED "."
		BLOCK[10] = ESC_RED "o"
		BLOCK[11] = ESC_RED "O"
		if ( USE_MULTICOLOR && USE_COLOR ) {
			BLOCK_LEN = 12
			BLOCK_RTT_MIN = 20
			BLOCK_RTT_MAX = 220
		} else {
			BLOCK_LEN = 4
			BLOCK_RTT_MIN = 75
			BLOCK_RTT_MAX = 225
		}
	}

	RTT_MIN = ENVIRON["RTT_MIN"]
	RTT_MAX = ENVIRON["RTT_MAX"]

	if ( int(RTT_MIN) > 0 && int(RTT_MAX) > 0 ) {
		BLOCK_RTT_MIN = int(RTT_MIN)
		BLOCK_RTT_MAX = int(RTT_MAX)
	} else if ( int(RTT_MIN) > 0 ) {
		BLOCK_RTT_MIN = int(RTT_MIN)
		BLOCK_RTT_MAX = BLOCK_RTT_MIN * (BLOCK_LEN - 1)
	} else if ( int(RTT_MAX) > 0 ) {
		BLOCK_RTT_MAX = int(RTT_MAX)
		BLOCK_RTT_MIN = int(BLOCK_RTT_MAX / (BLOCK_LEN - 1))
	}

	BLOCK_RTT_RANGE = BLOCK_RTT_MAX - BLOCK_RTT_MIN
	print_response_legend()
}

{
	if ( $0 ~ /^PING / && DESTINATION == "Unknown" ) {
		split($0, parts, " ")
		DESTINATION = parts[2]
		if ( IS_TERMINAL ) {
			printf( "\033]0;prettyping %s\007", DESTINATION )
		}
	}

	if ( $0 ~ /^[0-9]+ bytes from .*[:,] icmp_[rs]eq=[0-9]+ (ttl|hlim)=[0-9]+ time=[0-9.]+ *ms/ ) {

		rtt = $4 + 0
		seq = int($2)

		other_line_finished_repeating()

		if ( $0 ~ /DUP!/ ) {
			print_newlines_if_needed()
			print_received_response_colored(rtt, ESC_CYAN)
			dup_count++
			store(lastn_lost, 0)

		} else if ( seq <= last_seq && seq != 0 ) {
			print_newlines_if_needed()
			print_received_response_colored(rtt, ESC_MAGENTA)
			oop_count++
			process_rtt(rtt)
			received++
			store(lastn_lost, 0)
			last_seq = seq

		} else {
			while ( last_seq < seq - 1 ) {
				lost_a_packet()
			}
			print_newlines_if_needed()
			print_received_response(rtt)
			last_seq = seq
			process_rtt(rtt)
			received++
			store(lastn_lost, 0)
		}

		print_statistics_bar_if_terminal()

	} else if ( $0 ~ /^.*onnected to.*, seq=[0-9]+ time=[0-9.]+ *ms/ ) {
		other_line_finished_repeating()

		seq = $0
		sub(/.* seq=/, "", seq)
		seq = int(seq)

		rtt = $0
		sub(/.* time=/, "", rtt)
		rtt = rtt + 0

		process_rtt(rtt)

		while ( last_seq < seq - 1 ) {
			lost_a_packet()
		}

		print_newlines_if_needed()
		print_received_response(rtt)

		last_seq = seq
		received++
		store(lastn_lost, 0)

		print_statistics_bar_if_terminal()

	} else if ( $0 == "" ) {
		# Do nothing
	} else if ( $0 == "error shutting down ssl" ) {
		# Ignore httping ssl errors
	} else if ( $0 ~ /^Request timeout for icmp_seq [0-9]+/ ) {
		other_line_finished_repeating()

		gsub(/.* icmp_seq /, "")
		seq = int($0)

		while ( last_seq < seq ) {
			lost_a_packet()
		}

		print_statistics_bar_if_terminal()

	} else if ( $0 ~ /^SIGWINCH$/ ) {
		get_terminal_size()

		if ( IS_PRINTING_DOTS ) {
			if ( CURR_COL >= COLUMNS-1 ) {
				# Not enough space
			} else {
				printf( ESC_NEXTLINE ESC_NEXTLINE ESC_CURSORUP ESC_CURSORUP )
				printf( "\033[" (CURR_COL+1) "G" ESC_DEFAULT ESC_ERASELINEEND )
			}

			print_newlines_if_needed()
			print_statistics_bar_if_terminal()
		}
	} else {
		other_line_is_printed()
		original_line = $0
		gsub(/icmp_seq[= ][0-9]+/, "")
		if ( $0 == other_line ) {
			other_line_times++
			if ( IS_TERMINAL ) {
				other_line_is_repeated()
			}
		} else {
			other_line_finished_repeating()
			other_line = $0
			other_line_times = 1
			printf( "%s\n", original_line )
		}
	}

	fflush()
}'
